# Generated by Django 5.1.4 on 2024-12-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_remuneração_funcionario_remuneracao_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
